@startuml
object BufferDesc
BufferDesc : tag : BufferTag
BufferDesc : buf_id : Buffer
object BufferDescriptors

object BufferBlocks
object page

object buffered_file

object BufferTag
BufferTag : rnode
BufferTag : forkNum
BufferTag : blockNum

BufferDescriptors *-- "NBuffers" BufferDesc
page <|-- BufferDesc
BufferBlocks *-- "NBuffers" page
buffered_file <|-- BufferDesc
BufferTag <|-- BufferDesc
@enduml